### PR TITLE
Add cart_rule_lang in Check And Fix to delete old cart rule's names.

### PR DESCRIPTION
**Pull request by Uebix**
Fix to prevent Duplicate entry for key 'PRIMARY'.

### CODE REVIEW

**Comment by MathiasReker** [comment]
What is status on this?

**Comment by Uebix** [comment]
@MathiasReker it's open after one year

**Comment by MathiasReker** [comment]
@khouloudbelguith @eternoendless there are many good PR's open in this module. Can some of those get reviewed? :)

**Comment by MathiasReker** [comment]
I think pscleaner needs a little focus :-) It could be very nice to have a new version released 👍

**Comment by PierreRambaud** [comment]
Thanks @MathiasReker

**Pull request merged**
