### PR TITLE
Remove data from category_group when cleaning catalog. 

### PR DESCRIPTION
**Pull request by thoma202**
This allows to recreate categories with same id

### CODE REVIEW

**Comment by MathiasReker** [comment]
What is status on this?

**Comment by MathiasReker** [comment]
Rebased: https://github.com/PrestaShop/pscleaner/pull/36

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/pscleaner/pull/38

**Comment by Progi1984** [comment]
Hello @thoma202, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Pull request closed without merging**
