### PR TITLE
Fix missing table in Catalog Related Tables

### PR DESCRIPTION
**Pull request by prestarocket**
Attribute table is not truncated and they are issues with import

### CODE REVIEW

**Comment by MathiasReker** [comment]
What is status on this?

**Comment by prestarocket** [comment]
> What is status on this?

it s still open..

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/pscleaner/pull/38

**Comment by PierreRambaud** [comment]
Thanks @prestarocket

**Pull request merged**
