### PR TITLE
Hook "actionPSCleanerGetModulesTables" to get modules tables

### PR DESCRIPTION
**Pull request by PrestaEdit**
Hook "actionPSCleanerGetModulesTables" to get modules tables

### CODE REVIEW

**Comment by PrestaEdit** [comment]
=(

**Comment by MathiasReker** [comment]
What is status on this?

**Comment by MathiasReker** [comment]
Rebased: https://github.com/PrestaShop/pscleaner/pull/37

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/pscleaner/pull/38

**Comment by PrestaEdit** [comment]
Until #38 is not merged, it's not fixed.
Until #37 was made to fixed this one, on Feburary: it's really not fixed.

Say me that it's fixed while it is. Or it's bullshit.

**Comment by MathiasReker** [comment]
@PrestaEdit You are right, my wording was not clear. What I meant was that I included your PR in a refaco. There are many PR's open in PS cleaner that is not rebased. I guess this is a part of the reason why the module is not updated. Also I know that the PrestaShop developers are working hard on the core. To speed up the process I made this refaco. I am in favor of a new official release too.

**Comment by PrestaEdit** [comment]
Of course, if the PR's was checked at the right time and not 4 years after, it will be not the case. It's not why it's not merged: it's because submodules are not checked/taken in consideration.

**Comment by matks** [comment]
> Of course, if the PR's was checked at the right time and not 4 years after, it will be not the case. It's not why it's not merged: it's because submodules are not checked/taken in consideration.

Hi @PrestaEdit ,

I'm sorry to read that, I'm sad as you are about this PR not reviewed after 4 years 😞 
Although there's nothing I can do to fix this global issue (= PRs on modules getting stale for weeks, then months, then years) I can give some context about why we are in this situation

As you probably know, these las 4 years there was a lot of trouble at PrestaShop. One of the consequences of these sad events is that the whole team working on the opensource project has changed (for example I'm a member of the "new team" 😛 as I joined the crew on June of 2018). Like a ship, a new team needs some time to be at max speed so for many years there was a big slow in the Pull Requests review and management.

We are now doing a lot better than 2017 or 2018 but there is still a huge stream of pull requests overflowing the main repository [PrestaShop/PrestaShop](https://github.com/PrestaShop/PrestaShop/). That's a great thing as it proves the project is alive and well, but we are mainly focusing on this stream of pull requests that we barely are able to handle (= review). Believe it or not, we are merging more and more PRs each month, and yet, the number of open PRs keep increasing (more than 400 right now) ! It seems the more we review, the more people are happy to see the project moving forward, the more pull requests they submit 😆 ... sometime it looks like an endless cycle ...

Unfortunately, because of that huge activity on the main repository, the module repositories come second.
Each of the Core member has its own share of work, which includes bug fixes, new features, code review, documentation writing, automated tests writing, but also discussing with people through multiple channels (github, gitter, twitter, the forum ...), triaging issues to locate the critical / most relevant ones, doing some refactoring, some technical project management (like gathering issues alike together), making sure we have up-to-date docker images, tracking bad or missing translations, doing some workflow maintenance like opening/merging/closes PRs and git branches, maintaining the UI Kit (yes, I have not forgotten [your PR on it](https://github.com/PrestaShop/prestashop-ui-kit/pull/62)) ... there is a very huge pile of work for our small team.

Let's say we are never empty handed 😅 (you can see the big picture on the [public roadmap](https://github.com/PrestaShop/PrestaShop/projects/1) here: by the way you can see some modules are getting some highlight in the roadmap !

You might also wonder why it is taking so much time to review pull requests ?

Actually, reviewing a PR is not hard. Can be bothering or very long, especially with [4600 lines PRs](https://github.com/PrestaShop/PrestaShop/pull/13733), but what is *really* hard is clicking on this "approve" button.
Because when we approve a PR, we become responsible of introducing this change into the (already complex) PrestaShop project, and if this creates issues, be it bugs, design flaws, performance issues, even worse a security vulnerability, we consider ourselves responsibles of the failure ...

That's why when we look at PR, we ask ourselves:
"Is this code a good change ? Is it well written ? Is it understandable ? Is it bug free ? If it fixes a bug or brings a new feature, is the technical choice a good one ? Is it going to live well with the future of PrestaShop, what we have planned ? If it's CSS, is it going to live well with Right-To-Left Languages ? Is it going to behave well if we activate multi-shop mode ? Is it going to work even with bad network conditions or a small server with limited performances (this one is especially relevant for SQL queries) ?"

And these questions are even harder to answer when the PR is related to an area of the codebase that we dont know (yet). Which happens quite a lof to us, people who started working on PrestaShop only 1 year ago, as this is a very large codebase with a lot of history behind.

In order to overcome this endless tide of Pull Requests incoming, we are currently trying to hire new Core Developers to get some more people to review 😄 and also we are considering the possibility to welcome volunteers in the core team (= people who would have the merge rights on the repository without being a PrestaShop employee), but this requires a lot of legal/compliance stuff to be sorted out before we can do it.

So if you're as unhappy as we are about the current situation, what can you do ?

Well right now we definitely do not need more PRs 😆 but actually we need more reviews. And this is what you can do:

One of the big blockers for a PR is when we face a PR targeting an area of the codebase we dont know. It's very hard to approve or not such a PR as we fear we are approving something irrelevant, wrong, or full of bugs 😱. But if *you* have the knowledge, you too can review it and even "approve" it (I think you have the approve button, right ?). If you write in a comment on the PR "I have checked this PR, I confirm this works for usecases X and Y, even in multishop" this will help us a lot because we know you have a huge experience on PrestaShop so we know your validation has a lot of value 😉 

Lastly, I'm sorry again for seeing your contribution has spent so much time unreviewed, I just want you to do we are doing everything we can to not let this happen. But it'll take time before we can 1) overcome the stream of incoming PRs and 2) be able to review old PRs that were submitted recently.

**Comment by Progi1984** [comment]
Hello @PrestaEdit, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Pull request closed without merging**
