### PR TITLE
Add additional inforrmative output to the truncation operations

### PR DESCRIPTION
**Pull request by drzraf**
Output SQL TRUNCATE and other DELETE/UPDATE statements that got run when sales or catalog are requested for cleanup.

### CODE REVIEW

**Comment by drzraf** [comment]
ping ?

**Comment by drzraf** [comment]
ping?

**Comment by Misiak4** [comment]
Yeah this is true, I had a lot of problems too... I have another tables marked what need to be cleaned / truncated too...because I had issues. I need to create pull request for it

**Comment by MathiasReker** [comment]
What is status on this?

**Comment by MathiasReker** [comment]
@drzraf would you rebase on my fork? I am refactoring the module here: https://github.com/PrestaShop/pscleaner/pull/38

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Hello @drzraf , thanks for your contribution, would you mind to rebase your pull request? Thanks

**Pull request closed without merging**
