### PR TITLE
Add cron job and optimization params

### PR DESCRIPTION
**Pull request by djbuch**

### CODE REVIEW

**Comment by MathiasReker** [comment]
What is status on this?

**Comment by MathiasReker** [comment]
Con jobs added in a refacto here: https://github.com/PrestaShop/pscleaner/pull/38

**Comment by PierreRambaud** [comment]
PR really too old.
We're sorry for what happened. I'm closing this one, Don't hesitate to reopen if needed.

**Comment by PierreRambaud** [comment]
If you need more information, you can read https://github.com/PrestaShop/pscleaner/pull/8#issuecomment-513701816

**Pull request closed without merging**
