### PR TITLE
Improve Optimizazion and Clean function

### PR DESCRIPTION
**Pull request by HartLarsson**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | When we remove carts that are not in ps_order and are old then 1 month leaves a lot of ps_guests without a matching ps_cart, so we need to remove them
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | None
| How to test?  |

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you please rebase your branch on the dev branch?

**Comment by HartLarsson** [comment]
> Could you please rebase your branch on the dev branch?

I did sorry :)

**Comment by PierreRambaud** [comment]
> > Could you please rebase your branch on the dev branch?
> 
> I did sorry :)

It's weird, you include commits that do not belong to your pull request:
image

**Comment by HartLarsson** [comment]
> > > Could you please rebase your branch on the dev branch?
> > 
> > 
> > I did sorry :)
> 
> It's weird, you include commits that do not belong to your pull request:
> image

mmmh maybe i did something wrong on my pull request side?

**Pull request closed without merging**
